---
title: "Module 10 - Causal Inference"
editor: source
---

<!-- 
See issue with underscores in MathJax equations here: https://gohugo.io/content-management/formats/#issues-with-markdown
The solution, put backticks (`) around the LaTeX equation
-->

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  tex2jax: {
    inlineMath: [['$','$'], ['\\(','\\)']],
    displayMath: [['$$','$$'], ['\[','\]']],
    processEscapes: true,
    processEnvironments: true,
    skipTags: ['script', 'noscript', 'style', 'textarea', 'pre'],
    TeX: { equationNumbers: { autoNumber: "AMS" },
         extensions: ["AMSmath.js", "AMSsymbols.js"] }
  }
});
</script>

<script type="text/javascript" async src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML">
</script>

### Overview

Frequently, organizations want to use data not to make predictions, but to better understand the world and to understand the consequences of decisions. In many contexts,
this can be handled by randomized experimentation, as is seen in A/B tests or randomized controlled trials. However, it is not always possible to perform experiments.
Causal inference is a field that studies how to determine causation from observational data. Causal inference requires careful consideration of the potential confounding 
factors that exist in a given situation, but if correct assumptions can be made about those causal inference gives design principles for statistical or machine learning
models that can allow us to infer how a given action or intervention would impact a variable of interest.

The Minimal Viable Product Demo is due this week

### Learning Objectives

* Difference between prediction and causal inference 
* Confounders and basic DAGs
* Predicting Causal Effects with BART or Linear Regression



### Readings

* __CIBT__ : [Causal Inference for the Brave and True](https://matheusfacure.github.io/python-causality-handbook/landing-page.html):  Chapter 1, 13, 17
* __MLStory__: [Patterns, Predictions, and Actions](https://mlstory.org) Chapters 9 and 10



### Videos

* Software Carpentries [git tutorial](https://swcarpentry.github.io/git-novice/index.html)
* [Learn Git Branching interactive tutorial](https://learngitbranching.js.org/)
* [usethis package](https://usethis.r-lib.org/index.html)
* [Web APIs Book Club Page](https://dslc-io.github.io/club-wapir/) I recommend the intro slides and the httr2 specific slides.


